// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrmcnenpjifzdnpjljwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhybWNuZW5wamlmemRucGpsandwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3Mzc2ODksImV4cCI6MjA2MDMxMzY4OX0.5aGQ-77qE1Nqi7vHuv_yRBdL4pp9YTY6tCzxKoLJ9w4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);