
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabaseTypes';

const SUPABASE_URL = "https://ytikjzvtamgrkumnolil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0aWtqenZ0YW1ncmt1bW5vbGlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTMwNTgsImV4cCI6MjA2MTQyOTA1OH0.pKFOKt5r_ZewrWvvZFNDp0DPgf_WPZXp2Y8csSmzW4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
